spring:
  application:
    name: education-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/education-management-system
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


cloudflare:
  r2:
    bucketName: education-management-system
    accountId:
    accessKey:
    secretKey:

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug