spring:
  application:
    name: education-management-system

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      database: ${REDIS_DATABASE}
      password: ${REDIS_PASSWORD}

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

cloudflare:
  r2:
    bucketName: ${CLOUDFLARE_R2_BUCKET_NAME}
    accountId: ${CLOUDFLARE_R2_ACCOUNT_ID}
    accessKey: ${CLOUDFLARE_R2_ACCESS_KEY}
    secretKey: ${CLOUDFLARE_R2_SECRET_KEY}
    publicUrl: ${CLOUDFLARE_R2_PUBLIC_URL}

logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

auth:
  jwt:
    secretKey: ${AUTH_JWT_SECRET_KEY}
  bcrypt:
    pepper: ${AUTH_BCRYPT_PEPPER}